# Generated by Django 4.2.3 on 2023-11-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='track.timestampmixin')),
                ('name', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, max_length=50, null=True)),
            ],
            bases=('track.timestampmixin', models.Model),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='track.timestampmixin')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم')),
                ('typee', models.CharField(blank=True, choices=[('عامل', 'عامل'), ('موظف', 'موظف')], max_length=50, null=True)),
                ('jobTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.departement')),
            ],
            bases=('track.timestampmixin', models.Model),
        ),
    ]
