# Generated by Django 3.2.23 on 2024-02-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0004_contract_contractdate'),
        ('collect', '0002_alter_collectrequest_clientt'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectrequest',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء التحصيل'),
        ),
        migrations.AlterField(
            model_name='collectrequest',
            name='clientt',
            field=models.ManyToManyField(to='clientManager.FollowContractServices', verbose_name='متابعات التحصيل'),
        ),
    ]
