# Generated by Django 3.2.23 on 2024-02-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20240212_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectrequest',
            old_name='daftr_serial',
            new_name='daftrSerial',
        ),
    ]
