# Generated by Django 3.2.24 on 2024-02-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0004_contract_contractdate'),
        ('collect', '0004_rename_daftr_serial_collectrequest_daftrserial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectrequest',
            name='clientt',
            field=models.ManyToManyField(related_name='collect_request_clients', to='clientManager.Client', verbose_name='متابعات التحصيل'),
        ),
    ]
