# Generated by Django 5.0.2 on 2024-02-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_alter_collectrequest_clientt'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectrequest',
            name='confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
