# Generated by Django 4.2.3 on 2023-11-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='track.timestampmixin')),
                ('depart', models.CharField(blank=True, default='ادخال البيانات', max_length=50, null=True)),
                ('person', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.TextField(blank=True, max_length=350, null=True)),
            ],
            bases=('track.timestampmixin', models.Model),
        ),
    ]
