# Generated by Django 4.2.3 on 2023-11-11 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='track.timestampmixin')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('counter', models.IntegerField(blank=True, default=0, null=True)),
            ],
            bases=('track.timestampmixin', models.Model),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='track.timestampmixin')),
                ('serial', models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='الرقم التعريفى')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('building', models.CharField(blank=True, help_text='تفاصيل العمارة السكنية', max_length=150, null=True)),
                ('apart', models.CharField(blank=True, help_text='تفاصيل الشقه', max_length=150, null=True)),
                ('details', models.TextField(blank=True, help_text='اى تفاصيل إخرى للعنوان', max_length=250, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, null=True)),
                ('serviceId', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='clientManager.area')),
            ],
            bases=('track.timestampmixin', models.Model),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='track.timestampmixin')),
                ('notes', models.TextField(blank=True, max_length=250, null=True)),
                ('clientt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clientManager.client')),
            ],
            bases=('track.timestampmixin', models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('typee', models.CharField(blank=True, default='شهرى', max_length=50, null=True)),
                ('priceType', models.CharField(blank=True, default='شهرى', max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowContractServices',
            fields=[
                ('timestampmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='track.timestampmixin')),
                ('ecd', models.DateField(blank=True, null=True, verbose_name='تاريخ  التحصيل المفترض')),
                ('collcetStatus', models.CharField(blank=True, choices=[('wecd', 'فى انتظار ميعاد التحصيل'), ('pr', 'مطلوب الدفع'), ('pip', 'جارى الدفع'), ('pd', 'تم الدفع'), ('lp', 'متأخر الدفع')], db_index=True, default='wecd', max_length=5, null=True)),
                ('deservedAmount', models.IntegerField(blank=True, null=True, verbose_name='المبلغ المطلوب تحصيله')),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('clientt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fclient', to='clientManager.client')),
                ('contractt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcontract', to='clientManager.contract')),
            ],
            bases=('track.timestampmixin', models.Model),
        ),
        migrations.AddField(
            model_name='contract',
            name='servicee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='clientManager.service'),
        ),
    ]
