# Generated by Django 3.2.23 on 2023-11-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='apart',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' الشقه'),
        ),
        migrations.AlterField(
            model_name='client',
            name='building',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' العمارة '),
        ),
        migrations.AlterField(
            model_name='client',
            name='details',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name=' تفاصيل  للعنوان'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='رقم التليفون'),
        ),
        migrations.AlterField(
            model_name='client',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='clientManager.area', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='client',
            name='serial',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='السريال'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الشارع'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='clientt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clientManager.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='servicee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='clientManager.service', verbose_name='الخدمة'),
        ),
        migrations.AlterField(
            model_name='followcontractservices',
            name='clientt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fclient', to='clientManager.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='followcontractservices',
            name='collcetStatus',
            field=models.CharField(blank=True, choices=[('wecd', 'فى انتظار ميعاد التحصيل'), ('pr', 'مطلوب الدفع'), ('pip', 'جارى الدفع'), ('pd', 'تم الدفع'), ('lp', 'متأخر الدفع')], db_index=True, default='wecd', max_length=5, null=True, verbose_name='حالة التحصيل'),
        ),
        migrations.AlterField(
            model_name='followcontractservices',
            name='contractt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcontract', to='clientManager.contract', verbose_name='التعاقد'),
        ),
        migrations.AlterField(
            model_name='followcontractservices',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ملاحظات'),
        ),
    ]
