# Generated by Django 3.2.23 on 2023-11-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0002_auto_20231129_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='رقم التليفون'),
        ),
    ]
