# Generated by Django 3.2.23 on 2023-12-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientManager', '0003_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contractDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ  التعاقد'),
        ),
    ]
